export const taskArray = [
  {
    name: "heart",
    level: "5x5",
    matrix: ["_x_x_", "xxxxx", "xxxxx", "_xxx_", "__x__"],
  },
  {
    name: "flag",
    level: "5x5",
    matrix: ["_xxxx", "_xxxx", "_xxxx", "_x___", "_x___"],
  },
  {
    name: "tower",
    level: "5x5",
    matrix: ["x_x_x", "_xxx_", "_xxx_", "_xxx_", "_x_x_"],
  },
  {
    name: "tree",
    level: "5x5",
    matrix: ["_xxx_", "xxxxx", "xxxxx", "__x__", "__x__"],
  },
  {
    name: "chair",
    level: "5x5",
    matrix: ["x____", "x____", "xxxx_", "x__x_", "x__x_"],
  },
  {
    name: "dog",
    level: "5x5",
    matrix: ["_x___", "xx___", "_x___", "_xxxx", "_x_x_"],
  },
  {
    name: "kite",
    level: "5x5",
    matrix: ["xxx__", "xx___", "x_x__", "___x_", "____x"],
  },
  {
    name: "dog",
    level: "10x10",
    matrix: [
      "______x___",
      "x_____xxx_",
      "x_____xxxx",
      "x_____xxxx",
      "_xxxxxx___",
      "_xxxxxx___",
      "_xxxxxx___",
      "_xxxxxx___",
      "_x____x___",
      "_xx___xx__",
    ],
  },
  {
    name: "ship",
    level: "10x10",
    matrix: [
      "_____x____",
      "____xx____",
      "___xxx____",
      "__xxxx____",
      "_xxxxx____",
      "_xxxxx____",
      "_____x____",
      "xxxxxxxxxx",
      "xx_x_x_xx_",
      "_xxxxxxx__",
    ],
  },
  {
    name: "cup",
    level: "10x10",
    matrix: [
      "_x__x__x__",
      "x__x__x___",
      "_x__x__x__",
      "__x__x__x_",
      "xxxxxxxx__",
      "x______xxx",
      "xxxxxxxx_x",
      "xxxxxxxxx_",
      "xxxxxxxx__",
      "_xxxxxx___",
    ],
  },
  {
    name: "mail",
    level: "10x10",
    matrix: [
      "xxxxxxxxxx",
      "xx______xx",
      "x_x____x_x",
      "x__x__x__x",
      "x___xx___x",
      "x________x",
      "x________x",
      "x________x",
      "x________x",
      "xxxxxxxxxx",
    ],
  },
  {
    name: "snoopy",
    level: "10x10",
    matrix: [
      "xxxxxx__x_",
      "___xxxxx__",
      "___xxxxx__",
      "___xx_____",
      "__xxxx____",
      "__xxxxxx__",
      "__xxxx____",
      "__xxxx_x__",
      "_xxxxxxx__",
      "xxxxxxxxxx",
    ],
  },
  {
    name: "mushroom",
    level: "15x15",
    matrix: [
      "____xxxxxxx____",
      "___xxxxxxxxx___",
      "__xxxxxxxxxxx__",
      "_xxxxxxxx__xxx_",
      "xxxxxxxxxx_xxxx",
      "xxxxxxxxxxxxxxx",
      "___xxxxxxxxx___",
      "____x_____x____",
      "___xx_____xx___",
      "___x_______x___",
      "__xx_______xx__",
      "__x___x_____x__",
      "__xx__xx_x_xx_x",
      "x__x_xx_xx_x_xx",
      "xxxxxxxxxxxxxxx",
    ],
  },
  {
    name: "axe",
    level: "15x15",
    matrix: [
      "______xxxx_____",
      "_____xx_xx__xx_",
      "____xx_xxx_xxx_",
      "____xxxxxxxxx__",
      "____xxxx_xxx___",
      "____xx__xxxxxxx",
      "_______xxx_xxxx",
      "______xxx_xxxxx",
      "_____xxx__xxxxx",
      "____xxx__xxxxx_",
      "___xxx___xxxx__",
      "__xxx__________",
      "_xxx___________",
      "xxx____________",
      "xx_____________",
    ],
  },
  {
    name: "duck",
    level: "15x15",
    matrix: [
      "_________xxx___",
      "________xxxxx__",
      "_______xxxx_xxx",
      "_______xxxxxxx_",
      "________xxxxx__",
      "_________xxx___",
      "________xxxxx__",
      "x_____xxxxxxxx_",
      "xxx__xxx___xxx_",
      "xxxxxxx_xxx_xx_",
      "_xxxxx_xxxx_xx_",
      "_xxxxxxxx__xx__",
      "__xxxxxxxxxx___",
      "____xx_xxx_____",
      "______xxxxxx___",
    ],
  },
  {
    name: "castle",
    level: "15x15",
    matrix: [
      "______x________",
      "______xx_______",
      "______xxx______",
      "xx_xx_x___xx_xx",
      "xxxxx_x___xxxxx",
      "x___x_x___x___x",
      "x_x_x_x___x_x_x",
      "x_x_xxxxxxx_x_x",
      "x_____________x",
      "x__x_______x__x",
      "x_xxx__x__xxx_x",
      "x__x__xxx__x__x",
      "x__x__xxx__x__x",
      "x_____xxx_____x",
      "xxxxxxxxxxxxxxx",
    ],
  },
  {
    name: "deer",
    level: "15x15",
    matrix: [
      "xx_xx______xx_x",
      "xx_xx_x__x_xx_x",
      "_xxxx_x__x_xx_x",
      "__xxxxx___xxxxx",
      "____xx_xxxxx___",
      "______xxxxxxx__",
      "_____x_x_xxxxx_",
      "____xxxxxxxxxxx",
      "___xxxxxxxxxxxx",
      "__xxxxxxxxxxxxx",
      "_xxxxxxxx_xxxxx",
      "_x_xxx____xxxxx",
      "_xxxxx____xxxxx",
      "__xxx____xxxxxx",
      "_________xxxxxx",
    ],
  },
  {
    name: "mouse",
    level: "15x15",
    matrix: [
      "____________xxx",
      "_____xxxx__xx_x",
      "___xxx__x__x_x_",
      "xxx_x__x___x___",
      "xx_____x___xx__",
      "_xxxx__xx___xx_",
      "____xx__xx___xx",
      "_____x___xxx__x",
      "_____xx____xx_x",
      "___xxxx_____xxx",
      "___x_x__xx___xx",
      "_____x__x____x_",
      "______x_x____x_",
      "_____xxxxx__xx_",
      "___xxx_xx_xxx__",
    ],
  },
];
